# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XfYKZr_t_g-CUj_QRuQ1ywi3PNbYxNHs
"""

import numpy as np
from keras.models import load_model

# Load the pre-trained generator model
generator = load_model('gan_model.h5')  # Replace with your model's filename

# Generate a random latent vector
latent_dim = 100  # Adjust this based on your model's latent dimension
random_latent_vector = np.random.normal(size=(1, latent_dim))

# Generate an image using the generator
generated_image = generator.predict(random_latent_vector)

# Post-process the generated image if needed (e.g., scaling pixel values)
generated_image = (generated_image + 1) / 2.0  # Adjust if necessary



# Display  the generated image
import matplotlib.pyplot as plt

plt.imshow(generated_image[0])
plt.axis('off')
plt.show()

# You can also save the image using libraries like PIL
from PIL import Image
generated_image_pil = Image.fromarray((generated_image[0] * 255).astype('uint8'))
generated_image_pil.save('generated_image.png')